name: Sketch compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: arduino/compile-sketches@v1
      with:
        sketch-paths: |
          - ./
        libraries: |
          - name: rc-switch
            version: 2.6.2
          - name: DallasTemperature
            version: 3.7.6
          - name: OneWire
            version: 2.3.3
